"""Add full name field to User model

Revision ID: 057948aa5c5a
Revises: 87ca81b4637f
Create Date: 2025-10-23 22:48:23.843954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057948aa5c5a'
down_revision = '87ca81b4637f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
